---
title: "Math-Physics Paris"
---

The Math-Physics Paris discussion group focuses on symmetries in modern physics, exploring their fundamental roles and recent developments across high energy physics, condensed matter physics, and mathematical physics.

## Organization 

We have two types of meetings:

(1) irregular project meetings,
(2) regular seminar meetings.

### Project Meetings

These are scheduled irregularly, depending on the availability of the professors and students involved in the project.

### Seminar Meetings

The purpose is to provide a shared reading space for students working on projects and to invite researchers from related fields to broaden perspectives. These two types of meetings will therefore alternate.

#### Time

14:00 Paris/08:00 New York/20:00 Beijing on Saturdays

(The time may be adjusted to accommodate speakers' availability.)

#### Venue:

- ENS Math Department --- Salle R3
- IMJ-PRG Jussieu --- 15-16-413

(The exact room may vary by week and will be announced via email.)

#### Zoom Link

Distributed via email.