---
title: "Jun 06, 2026"
---

## Speaker
Chenxi Zeng

### Theme
Boundary-bulk relation in topological orders

### Abstract
We study the relation between an anomaly-free n+1D topological order and its nD gapped boundary phases by the introducing the notion of morphism between two topological orders of the same dimension. We argue that the n+1D bulk anomaly-free topological order for a given nD gapped boundary phase is unique. We show that the n+1D “bulk ” phase is given by the “center” of the nD boundary phase. In other words, the geometric notion of the “bulk ” corresponds precisely to the algebraic notion of the “center”. We achieve this by first introducing the notion of a morphism between two (potentially anomalous) topological orders of the same dimension, then proving that the notion of the “bulk ” satisfies the same universal property as that of the “center” of an algebra in mathematics, i.e. “bulk = center”. The entire argument does notrequire us to know the precise mathematical description of a (potentially anomalous) topological order. This lecture closely follow the paper 1702.00673.

### Video  
[Video 2026-06-06](https://drive.google.com/file/d/1Wi3XEeNqxcjG_JrAgYbG4fFpveByVd2E/view?usp=sharing)

### Notes
/

### Resources  
- [Boundary-bulk relation in topological orders (Liang Kong, Xiao-Gang Wen, Hao Zheng)](https://arxiv.org/abs/1702.00673)