---
title: "Seminars"
---

- [Mar 15, 2025: TQFT (1) --- Axiomatic Construction of TQFT](2025-03-15.qmd)   
- [Mar 22, 2025: TQFT (2) --- Basic Concepts of Higher-form Symmetries & Yang-Mills Theory](2025-03-22.qmd)  
- [Mar 29, 2025: TQFT (3) --- Chiral Anomaly](2025-03-29.qmd)
- [Apr 05, 2025: TQFT (4) --- 't Hooft Anomaly](2025-04-05.qmd)   
- [Apr 12, 2025: TQFT (5) --- Homology Theory & Replica Method](2025-04-12.qmd)    
- [Apr 19, 2025: TQFT (6) --- Chern-Weil Theorem & Characteristic Classes](2025-04-19.qmd) 
- [May 06, 2025: TQFT (7) --- Wess-Zumino Condition](2025-05-06.qmd)  
- [May 10, 2025: TQFT (8) --- Topological K-theory](2025-05-10.qmd)  
- [May 17, 2025: TQFT (9) --- SPT Construction](2025-05-17.qmd)  
- [May 24, 2025: TQFT (10) --- Instanton](2025-05-24.qmd)  
- [Jun 07, 2025: TQFT (11) --- Brief Introduction to SymTFT](2025-06-07.qmd)
- [Jun 15, 2025: TQFT (12) --- Non-invertible Symmetries in 4d](2025-06-15.qmd)  
- [Jul 12, 2025: Geometric Quantization (1) --- WKB Method and Symplectic Geometry](2025-07-12.qmd)  
- [Jul 20, 2025: Geometric Quantization (2) --- Quantizable Condition and Maslov Technique](2025-07-20.qmd)
- [Jul 26, 2025: Geometric Quantization (3) --- A Complete Geometric Characterization of Quantizability](2025-07-26.qmd)
- [Aug 02, 2025: Spin Geometry (1) --- Differential Operators on Manifolds](2025-08-02.qmd)
- [Aug 09, 2025: Introduction to 2d Conformal Field Theory](2025-08-09.qmd)
- [Aug 16, 2025: Spin Geometry (2) --- The Analysis of Dirac-type Operators](2025-08-16.qmd)
- [Aug 23, 2025: Construction of Liouville Conformal Field Theory](2025-08-23.qmd)
- [Sep 01, 2025: Spin Geometry (3) --- Introduction to Clifford Algebra](2025-09-01.qmd)
- [Sep 06, 2025: Irrational CFTs from Coupled Anyon Chains with Non-invertible Symmetries?](2025-09-06.qmd)
- [Sep 13, 2025: Spin Geometry (4) --- Spin Groups and Spinors](2025-09-13.qmd)
- [Sep 20, 2025: Higher Gauge Theory and Group Cohomology](2025-09-20.qmd)
- [Sep 27, 2025: Spin Geometry (5) --- Spin Structure](2025-09-27.qmd)
- [Oct 11, 2025: Spin Geometry (6) --- Heat Equation and Heat Kernel](2025-10-11.qmd)
- [Oct 18, 2025: All's Well that Ends Well: Endpoint Bootstrap for Conformal Line Defects](2025-10-18.qmd)
- [Oct 25, 2025: Anomaly from Moving Defects for Continuous Symmetries](2025-10-25.qmd)
- [Nov 01, 2025: An Introduction to Studying 3D CFTs on the Fuzzy Sphere](2025-11-01.qmd)
- [Nov 08, 2025: Spin Geometry (7) --- Heat Kernel Proof of the Atiyah–Singer Index Theorem](2025-11-08.qmd)
- [Nov 15, 2025: Non-invertible Symmetries and SPT on Lattice](2025-11-15.qmd)
- [Nov 29, 2025: Quantum Groups as Global Symmetries (1)](2025-11-29.qmd)
- [Dec 06, 2025: Cluster Algebras and Scattering Diagrams (1)](2025-12-06.qmd)
- [Dec 13, 2025: Quantum Groups as Global Symmetries (2)](2025-12-13.qmd)
- [Dec 20, 2025: Quantum Groups as Global Symmetries (3)](2025-12-20.qmd)
- [Dec 27, 2025: An Introduction to Topological String Theory (1)](2025-12-27.qmd)
- [Jan 03, 2026: Renormalized Volume and Weil-Petersson Teichmüller Theory](2026-01-03.qmd)
- [Jan 10, 2026: On Boundary Conditions and Phases of Quantum Field Theories](2026-01-10.qmd)
- [Jan 11, 2026: An Introduction to Topological String Theory (2): Topological Sigma Model and Topological String](2026-01-11.qmd)
- [Jan 17, 2026: Returning to the Beauty of Mathematical Structure and the Depth of Natural Philosophy](2026-01-17.qmd)
- [Jan 24, 2026: Some Spectral Theory Problems in Condensed Matter Physics](2026-01-24.qmd)
- [Jan 31, 2026: Symmetric Gapped States and Symmetry-Enforced Gaplessness in 3-dimension](2026-01-31.qmd)
- [Feb 07, 2026: Anomalous Symmetries in Mixed-state Phases: a Perspective from Operator Algebras](2026-02-07.qmd)
- [Feb 14, 2026: Non-Invertible Kennedy-Tasaki Transformation and Applications to Gapless-SPT](2026-02-14.qmd)
- [Feb 21, 2026: An Introduction to Topological Modular Forms](2026-02-21.qmd)
- [Feb 28, 2026: On Boundary Conditions and Phases of Quantum Field Theories (2)](2026-02-28.qmd)
- [Mar 07, 2026: A Mini-course on Non-Archimedean Geometry (1)](2026-03-07.qmd)